stages:
  - build
  - test
  - notify

build-backend-code-job:
  stage: build
  script:
    - cd backend
    - mvn package -Dmaven.repo.local=${CI_PROJECT_DIR}/.m2/repository
  after_script:
    - echo "JOB_ID=$CI_JOB_ID" >> job.env
  cache:
    key: maven-cache
    paths:
      - ${CI_PROJECT_DIR}/.m2/repository
  artifacts:
    paths:
      - backend/target/
      - ${CI_PROJECT_DIR}/.m2/repository
    reports:
      dotenv:
        job.env
  rules:
    - changes: 
      - backend/**/*

semgrep-sast:
  stage: test
  variables:
    COMPILE: "false"
    SAST_JAVA_VERSION: 11
    MAVEN_REPO_PATH: ${CI_PROJECT_DIR}/.m2/repository
  needs:
    - build-backend-code-job
  artifacts:
    reports:
      sast: gl-sast-report.json

sonarqube-backend-sast:
  stage: test
  image: maven:3.8-openjdk-16
  variables:
     SONAR_USER_HOME: "${CI_PROJECT_DIR}/.sonar"
     GIT_DEPTH: "0"
  cache:
    key: "${CI_JOB_NAME}"
    paths:
      - .sonar/cache
  needs:
    - build-backend-code-job
  script:
    - cd backend
    - |
      mvn verify sonar:sonar \
      -Dsonar.qualitygate.wait=true \
      -Dsonar.projectKey=${SONAR_PROJECT_KEY_BACK} \
      -Dsonar.host.url=${SONARQUBE_URL} \
      -Dsonar.login=${SONAR_LOGIN_BACKEND} \
      -Dsonar.projectName=${SONAR_PROJECT_NAME} \
      -Dsonar.java.binaries=target/
 
telegram-notification-backend:
  stage: notify
  script:
    - 'curl -X POST -H "Content-Type: application/json" -d "{\"chat_id\": \"-1002218066565\", \"text\": \"Cергей Федотов собрал backend. Артефакты по ссылке: $CI_PROJECT_URL/-/jobs/$JOB_ID/artifacts/download?job=$CI_JOB_NAME\"}" https://api.telegram.org/bot5933756043:AAE8JLL5KIzgrNBeTP5e-1bkbJy4YRoeGjs/sendMessage'
  needs:
    - build-backend-code-job
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /send notification/
      changes: 
        - backend/**/*